### ISSUE TITLE
Error when exporting emodule to .tsv

### ISSUE THREAD

**Issue by jonakayser** [DC-analysis/DCscope#80]
With Shape-Out 2.6.0 on mac, I got the following error message when trying to export data to .tsv

Unhandled exception in Shape-Out version 2.6.0:
Traceback (most recent call last):
File "shapeout2/gui/export/e2data.py", line 46, in done
File "shapeout2/gui/widgets/wait_cursor.py", line 31, in wrapper
File "shapeout2/gui/export/e2data.py", line 88, in export_data
File "dclab/rtdc_dataset/export.py", line 281, in tsv
ValueError: Invalid feature name emodulus

When deactivating Young's modulus, the export goes through just fine.

**Comment by paulmueller** [comment]
I can reproduce this. The error only occurs if the Young's modulus (ancillary feature) has not been computed for at least one dataset. The current solution to the problem is to make sure that the Young's modulus settings are given for all datasets.

To fix this issue:

- make sure that all features that the user would like to export are actually available in all datasets
- display a warning that for datasets xy this is not the case (and NaNs will be exported)
- if the use still wants to export the data, write NaNs to the .tsv file for the given features

The fix should be feature-agnostic (i.e. it should also work like that for any other feature).
