### ISSUE TITLE
Fatal error "Failed to execute script Shapeout2Launcher" with latest R installed

### ISSUE THREAD

**Issue by sdespina** [DC-analysis/DCscope#98]
I installed the latest version but I can not run it on my computer. 
![ShapeOut 2 7 0 fatal error](https://user-images.githubusercontent.com/52213329/130628823-18b51903-f060-4cd9-87f8-5f283e90925b.PNG)

**Comment by paulmueller** [comment]
Can anyone else reproduce this?

**Comment by paulmueller** [comment]
@sdespina But the previous versions of Shape-Out (e.g. 2.6.9) worked on that computer, right?

**Comment by sdespina** [comment]
> @sdespina But the previous versions of Shape-Out (e.g. 2.6.9) worked on that computer, right?

Yes, i already reinstalled version 2.6.6. that I had before and works fine. I didn't try the other ones, cos I wanted to continue with my analysis. I can give it a try tomorrow

**Comment by sdespina** [comment]
Anything after version 2.6.6 gives me the same error message

**Comment by paulmueller** [comment]
@sdespina Could you please download this Shape-Out build with an enabled console: https://ci.appveyor.com/api/buildjobs/8s0a1xl158vikrk8/artifacts/build-recipes%2FOutput%2FShape-Out_2.7.1.post1_win_64bit_setup.exe

If you execute this build, a command prompt will pop up. Please post any error messages (screenshot is fine) that appear in that command prompt.

**Comment by paulmueller** [comment]
This issue is also related to #89. In the command line, you might see errors like this one:
![image](https://user-images.githubusercontent.com/2853022/133100779-f814b8d5-daf8-4031-b746-fcca3e1d8499.png)

This is also an issue with Windows support by rpy2: https://github.com/rpy2/rpy2/issues/721

A workaround for Windows users is to install R-3.6.3: https://cran.r-project.org/bin/windows/base/old/3.6.3/

I am closing this issue here (because it is not a Shape-Out bug), but I am pinning it until the upstream issue is eventually resolved.
